version: '3.3'

services:
    simuled:
      build: ./services/simuled
      command: gunicorn --bind 0.0.0.0:5000 --timeout 300  manage:app
      volumes:
        - ./services/simuled/:/usr/src/app/
      expose:
        - 5000
      env_file:
        - ./.env
      depends_on:
        - db

    db:
      image: postgres:alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.db

    nginx:
      build: ./services/nginx
      volumes:
        - ./services/nginx/js/:/home/app/simuled/js
      ports:
        - 443:443
      depends_on:
        - simuled

volumes:
    postgres_data:
