"""initial migration

Revision ID: 1bae897f6ce3
Revises: 
Create Date: 2022-05-11 21:30:59.041303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bae897f6ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aboutme', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_user_aboutme'), 'user', ['aboutme'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_aboutme'), table_name='user')
    op.drop_column('user', 'aboutme')
    # ### end Alembic commands ###
