"""ren der update

Revision ID: a1d4b3eb2711
Revises: fd6e360eced3
Create Date: 2022-08-03 10:50:20.168222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d4b3eb2711'
down_revision = 'fd6e360eced3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_img', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'room_img', 'user', ['userID'], ['userID'])
    # ### end Alembic commands ###
