"""x

Revision ID: b0a679406516
Revises: 
Create Date: 2022-06-10 11:27:33.216625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a679406516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lamp',
    sa.Column('lampID', sa.Integer(), nullable=False),
    sa.Column('lampName', sa.String(length=100), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('imgName', sa.String(length=1000), nullable=True),
    sa.Column('lampText', sa.String(length=1000), nullable=True),
    sa.Column('lampLongText', sa.String(length=10000), nullable=True),
    sa.Column('lampPrice', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('lampID')
    )
    op.create_table('user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('lamp')
    # ### end Alembic commands ###
