"""gltf

Revision ID: ddf137f8a8e7
Revises: b0a679406516
Create Date: 2022-06-10 12:28:24.334234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf137f8a8e7'
down_revision = 'b0a679406516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lamp', sa.Column('gltfName', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lamp', 'gltfName')
    # ### end Alembic commands ###
