"""added renders

Revision ID: fd6e360eced3
Revises: 26676a8ec332
Create Date: 2022-08-03 10:39:05.803511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6e360eced3'
down_revision = '26676a8ec332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_img',
    sa.Column('roomID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('imgName', sa.String(length=1000), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('roomID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_img')
    # ### end Alembic commands ###
