"""cart

Revision ID: 26676a8ec332
Revises: 9aef97046c8c
Create Date: 2022-06-17 15:04:47.955503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26676a8ec332'
down_revision = '9aef97046c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cartID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('lampID', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cartID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
