"""newInit2

Revision ID: e1412e0d5fcb
Revises: 
Create Date: 2022-08-10 14:46:36.501150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1412e0d5fcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cartID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('lampID', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cartID')
    )
    op.create_table('render',
    sa.Column('renderID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(length=100), nullable=True),
    sa.Column('renderName', sa.String(length=100), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('imgName', sa.String(length=1000), nullable=True),
    sa.Column('renderText', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('renderID')
    )
    op.create_table('user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=False),
    sa.Column('passwordHash', sa.String(length=120), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('currentOrder', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('firstName', sa.String(length=200), nullable=True),
    sa.Column('lastName', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('postalCode', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('lamp',
    sa.Column('lampID', sa.Integer(), nullable=False),
    sa.Column('lampName', sa.String(length=100), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('imgName', sa.String(length=1000), nullable=True),
    sa.Column('gltfName', sa.String(length=1000), nullable=True),
    sa.Column('lampText', sa.String(length=1000), nullable=True),
    sa.Column('lampLongText', sa.String(length=10000), nullable=True),
    sa.Column('userKeyID', sa.Integer(), nullable=True),
    sa.Column('lampPrice', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userKeyID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('lampID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lamp')
    op.drop_table('user')
    op.drop_table('render')
    op.drop_table('cart')
    # ### end Alembic commands ###
